name: Deploy SimpleMessagingApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build . -t dickypratamss/simple-messaging-app
      - name: Push docker image to docker hub
        run: docker push dickypratamss/simple-messaging-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull docker image
        run: docker pull dickypratamss/simple-messaging-app:latest
      - name: Delete old docker container
        run: docker rm -f simple-messaging-app
      - name: Running new docker container
        run: docker run -d -p 8080:8080 -p 4000:4000 --name simple-messaging-app dickypratamss/simple-messaging-app

      